// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Peer struct {
	Email       string
	PeerID      string
	InterfaceID string
	AllowedIp   string
	Config      string
	CreatedAt   time.Time
}

type Interface struct {
	ID         string
	Name       string
	Address    string
	ListenPort int64
	Mtu        int64
	Endpoint   string
	CreatedAt  time.Time
}

type AllowedEmail struct {
	InterfaceID string
	Email       string
	CreatedAt   time.Time
}
